### ISSUE TITLE
Unnecessarily long function

### ISSUE THREAD

**Issue by ghost** [8infy/UltraOS#1]
The function `kernel::runtime::ensure_loaded_correctly()` has an unnecessarily long if statement that can be replaced with a more suitable function like `kernel::compare_memory()`.

**Comment by d-tatianin** [comment]
You're right. 🙂 Reason is `ensure_loaded_correctly` was introduced very early on before `compare_memory` was even a thing.

**Comment by ghost** [comment]
By the way, why haven't you been online on Discord for the past two days?

**Comment by d-tatianin** [comment]
Trying to focus on work 😋
