### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by The-Jat** [8infy/UltraOS#3]
/home/mak/Downloads/Ultra/Kernel/Drivers/USB/XHCI/XHCI.cpp: In member function 'bool kernel::XHCI::initialize_command_ring()':
/home/mak/Downloads/Ultra/Kernel/Drivers/USB/XHCI/XHCI.cpp:262:32: error: cannot bind packed field 'link.kernel::LinkTRB::RingSegmentPointerLo' to 'unsigned int&'
  262 |     set_dwords_to_address(link.RingSegmentPointerLo, link.RingSegmentPointerHi, command_ring_page.address());
      |                           ~~~~~^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Kernel/CMakeFiles/Kernel.bin.dir/build.make:310: Kernel/CMakeFiles/Kernel.bin.dir/Drivers/USB/XHCI/XHCI.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:298: Kernel/CMakeFiles/Kernel.bin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Failed to build UltraOS!

**Comment by d-tatianin** [comment]
Yeah sorry no CI yet set up for the project so things like that happen :) This can be fixed by replacing it with `SET_DWORDS_TO_ADDRESS` . xHCI specifically is very WIP atm. Will fix this issue later today.
